version: "3.3"
services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    env_file:
      - devcontainer.env
      - devcontainer_user.env
    environment:
      - TZ=Asia/Tokyo
      - DB_DATABASE=devcontainer_testing
    volumes:
      - ..:/workspace:cached
      - ./workspace/php.ini:/usr/local/etc/php/php.ini:ro
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - devcontainer.env
      - devcontainer_user.env
    ports:
      - "8080:80"
    volumes:
      - ..:/var/devcontainer
      - ./web/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
  db:
    image: mariadb:10.5.9
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
    volumes:
      - laravel-devcontainer-mysql:/var/lib/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./db/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "8082:80"
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  laravel-devcontainer-mysql:
